version: '3.4'

services:
        topology-service:
                build: .
                volumes:
                        - .:/usr/src/app
                ports:
                        - 6556:8080
                environment:
                        env_file: ./env_vars.env
networks:
        nms-l2:
                driver: host

