version: '3.4'

services:
        topology-service:
                build: .
                volumes:
                        - .:/usr/src/app
                ports:
                        - 6556:8081
                environment:
                        env_file: ./env_vars.env
                network_mode: "host"

